Controllers/EnquiryController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Logging;
using PropertySite.Models;
using PropertySite.Data;

namespace PropertySite.Controllers
{
    public class EnquiryController : Controller
    {
        private readonly ILogger<EnquiryController> _logger;
        private readonly ApplicationDbContext _context;

        public EnquiryController(ILogger<EnquiryController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public async Task<IActionResult> Create(Guid? id)
        {
            if (id == null){
                return NotFound();
            }

            var property = await _context.Properties.FirstOrDefaultAsync(m => m.ID == id);
            if (property == null) {
                return NotFound();
            }
            return View(new Enquiry() {
                EnquiryID= Guid.NewGuid(),
                PropertyID = id.Value,
                CreatedDate = DateTime.Now,
            });
        }
    
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EnquiryID,PropertyID,Name,Text,CreatedDate")] Enquiry enquiry)
        {
            if (ModelState.IsValid) {
                Console.Out.WriteLine($"{enquiry.EnquiryID}, {enquiry.PropertyID}");
                _context.Enquiries.Add(enquiry);
                await _context.SaveChangesAsync();
                return Redirect($"/Home/Details/{enquiry.PropertyID}");
            }
            return View(enquiry);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Logging;
using PropertySite.Models;
using PropertySite.Data;
using System.Security.Claims;

namespace PropertySite.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _context;

        public HomeController(ILogger<HomeController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Properties.ToListAsync());
        }

        public IActionResult Create()
        {
            var userId =  User.FindFirst(ClaimTypes.NameIdentifier);
            return View(new Property() {
                UserID = userId.Value,
                CreatedDate = DateTime.Now,
            });
        }
    
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("UserID,ID,Description,Rent,CreatedDate")] Property property)
        {
            if (ModelState.IsValid) {
                _context.Add(property);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(property);
        }

        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null){
                return NotFound();
            }

            var property = await _context.Properties.Include(m => m.Enquiries).FirstOrDefaultAsync(m => m.ID == id);
            if (property == null) {
                return NotFound();
            }

            return View(property);
        }

        [Authorize]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null) {
                return NotFound();
            }

            var property = await _context.Properties.FindAsync(id);
            if (property == null) {
                return NotFound();
            }
            var userId =  User.FindFirst(ClaimTypes.NameIdentifier);
            if (property.UserID != userId.Value) {
                return Unauthorized();
            }
            return View(property);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("ID,UserID,Description,Rent,CreatedDate")] Property property)
        {
            if (id != property.ID) {
                return NotFound();
            }
            var userId =  User.FindFirst(ClaimTypes.NameIdentifier);
            if (property.UserID != userId.Value) {
                return Unauthorized();
            }

            if (ModelState.IsValid) {
                try {
                    _context.Update(property);
                    await _context.SaveChangesAsync();
                } catch (DbUpdateConcurrencyException) {
                    if (!PropertiesExists(property.ID)) {
                        return NotFound();
                    } else {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(property);
        }

        [Authorize]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null) {
                return NotFound();
            }

            var property = await _context.Properties.FirstOrDefaultAsync(m => m.ID == id);
            if (property == null) {
                return NotFound();
            }
            var userId =  User.FindFirst(ClaimTypes.NameIdentifier);
            if (property.UserID != userId.Value) {
                return Unauthorized();
            }

            return View(property);
        }

        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var userId =  User.FindFirst(ClaimTypes.NameIdentifier);
            var property = await _context.Properties.FindAsync(id);
            if (property.UserID != userId.Value) {
                return Unauthorized();
            }
            _context.Properties.Remove(property);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PropertiesExists(Guid id)
        {
            return _context.Properties.Any(e => e.ID == id);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Home/Create.cshtml
@model PropertySite.Models.Property

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Todo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <input type="hidden" asp-for="UserID" />
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rent" class="control-label"></label>
                <input asp-for="Rent" class="form-control" />
                <span asp-validation-for="Rent" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="CreatedDate" />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Home/Delete.cshtml
@model PropertySite.Models.Property

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Todo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Home/Details.cshtml
@model PropertySite.Models.Property
@using System.Security.Claims;

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Property</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rent)
        </dd>
    </dl>
</div>
<div>
    @if (User.Identity.IsAuthenticated && User.FindFirst(ClaimTypes.NameIdentifier).Value == Model.UserID) {
        <p>
            <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a>
            <a asp-controller="Enquiry" asp-action="Create" asp-route-id="@Model.ID">Create an Enquiry</a> |
            <a asp-action="Index">Back to List</a>
        </p>
    }else{
        <p>
            <a asp-controller="Enquiry" asp-action="Create" asp-route-id="@Model.ID">Create an Enquiry</a> 
        </p>
    }
</div>
<div>
    <h4>Enquiries</h4>
    @foreach (var item in Model.Enquiries)
    {
        <div>
            <h5>@item.Name</h5>
            <p>@item.Text</p>
        </div>
    }
</div>

Views/Home/Edit.cshtml
@model PropertySite.Models.Property

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Todo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <input type="hidden" asp-for="UserID" />
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rent" class="control-label"></label>
                <input asp-for="Rent" class="form-control" />
                <span asp-validation-for="Rent" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="CreatedDate" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Home/Index.cshtml

@model IEnumerable<PropertySite.Models.Property>
@using System.Security.Claims;

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
@if (User.Identity.IsAuthenticated) {
    <p>
        <a asp-action="Create">Create New</a>
    </p>
} else {
    <p>
        <a class="" asp-area="Identity" asp-page="/Account/Login">Login</a> or
        <a class="" asp-area="Identity" asp-page="/Account/Register">Register</a> to list a property!
    </p>
}
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rent)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rent)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedDate)
            </td>
            <td>
                @if (User.Identity.IsAuthenticated && User.FindFirst(ClaimTypes.NameIdentifier).Value == item.UserID) {
                    <p>
                        <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                    </p>
                }else{
                    <a asp-action="Details" asp-route-id="@item.ID">Details</a>
                }
            </td>
        </tr>
}
    </tbody>
</table>